### ISSUE TITLE
Symptomatic status

### ISSUE THREAD

**Issue by arronlacey** [arronlacey/Epilepsy-GATE-app#26]

**Comment by BeataFS** [comment]
Symptomatic epilepsies if stated as part of the  diagnosis  i.e. symptomatic focal epilepsy or  epilepsy due to stroke should be picked up by the epilepsy diagnosis ( and they have their own CUIs).  Others , when a head injury is mentioned  will be annotated by the  comorbidities rules   - then we  will have to decide whether we use a CUI for that comorbidity or somehow link it to a specific CUI for epilepsy due to this comorbidity - it all depends the certainty level I suppose .
